[package]
name = "hash-cmp"
version = "2.0.0"
edition = "2022"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.2"
hex-literal = "0.3.4"
